# Generated by Django 3.0.1 on 2020-03-01 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('date', models.DateField(default=datetime.date(2020, 3, 1))),
                ('minsal', models.IntegerField(blank=True, default=0)),
                ('maxsal', models.IntegerField(blank=True, default=100000)),
                ('jobtitle', models.TextField(max_length=20)),
                ('companyname', models.CharField(max_length=500)),
                ('minexp', models.IntegerField(default=0, max_length=10)),
                ('maxexp', models.IntegerField(default=3, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('jobdescription', models.TextField(max_length=500)),
                ('originaljoburl', models.URLField(blank=True)),
                ('jobportal', models.CharField(blank=True, max_length=20)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('jobtype', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtitle', models.CharField(blank=True, max_length=20)),
                ('Sortby', models.CharField(choices=[('DATE', 'DATE'), ('SALARY', 'SALARY'), ('EXPERIENCE', 'EXPERIENCE')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('savedjobs', models.TextField(max_length=50)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phonenumber', models.IntegerField(default=0, max_length=10)),
                ('workexperience', models.IntegerField(default=0, max_length=25)),
                ('skills', models.TextField(blank=True, default='a', max_length=200)),
                ('degree', models.CharField(default='s', max_length=50)),
                ('stream', models.CharField(default='A', max_length=30)),
                ('certifications', models.TextField(default='a', max_length=10)),
                ('additionalinfo', models.TextField(blank=True, default='a', max_length=100)),
                ('city', models.CharField(default='none', max_length=20)),
                ('state', models.CharField(default='none', max_length=15)),
                ('country', models.CharField(default='India', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
