# Generated by Django 3.0.1 on 2020-03-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200305_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='Example2',
        ),
    ]
