# Generated by Django 3.0.1 on 2020-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200305_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='workexperience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='companyname',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institutename',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='percentageorgrade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfoliolink',
            field=models.URLField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projectcompletionyear',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projectdescription',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projecttitle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yearsofworking',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
