# Generated by Django 3.0.1 on 2020-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200305_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institutename',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='percentageorgrade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfoliolink',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projectcompletionyear',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projectdescription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projecttitle',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='yearsofworking',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workexperience',
            field=models.IntegerField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(default='s', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(default='A', max_length=30),
        ),
    ]
