# Generated by Django 3.0.1 on 2020-03-06 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200305_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 6)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='maxexp',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='maxsal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
