# Generated by Django 3.0.1 on 2020-03-07 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200306_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 7)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
