# Generated by Django 3.0.1 on 2020-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200308_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additionalinfo',
            field=models.TextField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
    ]
