# Generated by Django 3.0.1 on 2020-03-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
