# Generated by Django 3.0.1 on 2020-03-09 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200308_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 9)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectdescription',
            field=models.TextField(max_length=500),
        ),
    ]
