# Generated by Django 3.0.1 on 2020-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200309_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('stream', models.CharField(max_length=30)),
                ('studyforyears', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('companyyow', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=30)),
                ('projectdescription', models.TextField(max_length=200)),
                ('projectyoc', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='companyyow',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projectdescription',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projecttitle',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projectyoc',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='studyforyears',
        ),
    ]
