# Generated by Django 3.0.1 on 2020-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200309_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='projects',
            name='email',
            field=models.EmailField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='extrainfo',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='linkedinprofileurl',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='phoneno',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='usertitle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
