# Generated by Django 3.0.1 on 2020-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200309_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phoneno', models.CharField(max_length=30)),
                ('linkedinprofileurl', models.CharField(max_length=30)),
                ('usertitle', models.CharField(max_length=30)),
                ('skills', models.TextField(max_length=100)),
                ('extrainfo', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='extrainfo',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='linkedinprofileurl',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='usertitle',
        ),
    ]
