# Generated by Django 3.0.1 on 2020-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200310_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='companyname1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='companyname2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='companyname3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='companyyow1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='companyyow2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='companyyow3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='designation1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='designation2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='designation3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='institute1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='institute2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='institute3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedinprofileurl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phoneno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectdescription1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectdescription2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectdescription3',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projecttitle1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projecttitle2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projecttitle3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectyoc1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectyoc2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projectyoc3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='stream1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='stream2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='stream3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='studyforyears1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='studyforyears2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='studyforyears3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
