# Generated by Django 3.0.1 on 2020-03-19 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_resume_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 19)),
        ),
    ]
