# Generated by Django 3.0.1 on 2020-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200324_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
