# Generated by Django 3.0.1 on 2020-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200324_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
